/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

module router_fifo(clock, resetn, soft_reset, write_enb, read_enb, data_in, lfd_state, empty, full, data_out);
  input clock;
  wire clock;
  input resetn;
  wire resetn;
  input soft_reset;
  wire soft_reset;
  input write_enb;
  wire write_enb;
  input read_enb;
  wire read_enb;
  input [7:0] data_in;
  wire [7:0] data_in;
  input lfd_state;
  wire lfd_state;
  output empty;
  wire empty;
  output full;
  wire full;
  output [7:0] data_out;
  reg [7:0] data_out;
  wire [3:0] _000_;
  wire [8:0] _001_;
  wire [8:0] _002_;
  wire [3:0] _003_;
  wire [8:0] _004_;
  wire [8:0] _005_;
  wire [3:0] _006_;
  wire [8:0] _007_;
  wire [8:0] _008_;
  reg [3:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire [3:0] _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire [1:0] _048_;
  wire _049_;
  wire [2:0] _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire [1:0] _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire [8:0] _074_;
  wire [8:0] _075_;
  wire [8:0] _076_;
  wire [8:0] _077_;
  wire [8:0] _078_;
  wire [8:0] _079_;
  wire [8:0] _080_;
  wire [8:0] _081_;
  wire [8:0] _082_;
  wire [8:0] _083_;
  wire [8:0] _084_;
  wire [8:0] _085_;
  wire [8:0] _086_;
  wire [8:0] _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire [8:0] _104_;
  wire [4:0] _105_;
  wire _106_;
  wire _107_;
  wire [5:0] _108_;
  wire [5:0] _109_;
  wire [7:0] _110_;
  wire [7:0] _111_;
  wire [4:0] _112_;
  wire [4:0] _113_;
  wire [4:0] _114_;
  wire [3:0] _115_;
  wire [3:0] _116_;
  wire [3:0] _117_;
  wire [3:0] _118_;
  wire [3:0] _119_;
  wire [3:0] _120_;
  wire [5:0] _121_;
  wire [5:0] _122_;
  wire [5:0] _123_;
  wire [5:0] _124_;
  wire [4:0] _125_;
  wire [4:0] _126_;
  wire [4:0] _127_;
  wire [5:0] _128_;
  wire [5:0] _129_;
  wire [5:0] _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  reg [4:0] count;
  reg [8:0] \mem[0] ;
  reg [8:0] \mem[10] ;
  reg [8:0] \mem[11] ;
  reg [8:0] \mem[12] ;
  reg [8:0] \mem[13] ;
  reg [8:0] \mem[14] ;
  reg [8:0] \mem[15] ;
  reg [8:0] \mem[1] ;
  reg [8:0] \mem[2] ;
  reg [8:0] \mem[3] ;
  reg [8:0] \mem[4] ;
  reg [8:0] \mem[5] ;
  reg [8:0] \mem[6] ;
  reg [8:0] \mem[7] ;
  reg [8:0] \mem[8] ;
  reg [8:0] \mem[9] ;
  reg [5:0] pl_count;
  reg [3:0] rd_ptr;
  reg [3:0] wrt_ptr;
  always @(posedge clock)
    if (_094_) \mem[15] [0] <= _001_[0];
  always @(posedge clock)
    if (_094_) \mem[15] [1] <= _001_[1];
  always @(posedge clock)
    if (_094_) \mem[15] [2] <= _001_[2];
  always @(posedge clock)
    if (_094_) \mem[15] [3] <= _001_[3];
  always @(posedge clock)
    if (_094_) \mem[15] [4] <= _001_[4];
  always @(posedge clock)
    if (_094_) \mem[15] [5] <= _001_[5];
  always @(posedge clock)
    if (_094_) \mem[15] [6] <= _001_[6];
  always @(posedge clock)
    if (_094_) \mem[15] [7] <= _001_[7];
  always @(posedge clock)
    if (_094_) \mem[15] [8] <= _001_[8];
  always @(posedge clock)
    if (_093_) \mem[14] [0] <= _001_[0];
  always @(posedge clock)
    if (_093_) \mem[14] [1] <= _001_[1];
  always @(posedge clock)
    if (_093_) \mem[14] [2] <= _001_[2];
  always @(posedge clock)
    if (_093_) \mem[14] [3] <= _001_[3];
  always @(posedge clock)
    if (_093_) \mem[14] [4] <= _001_[4];
  always @(posedge clock)
    if (_093_) \mem[14] [5] <= _001_[5];
  always @(posedge clock)
    if (_093_) \mem[14] [6] <= _001_[6];
  always @(posedge clock)
    if (_093_) \mem[14] [7] <= _001_[7];
  always @(posedge clock)
    if (_093_) \mem[14] [8] <= _001_[8];
  always @(posedge clock)
    if (_092_) \mem[13] [0] <= _001_[0];
  always @(posedge clock)
    if (_092_) \mem[13] [1] <= _001_[1];
  always @(posedge clock)
    if (_092_) \mem[13] [2] <= _001_[2];
  always @(posedge clock)
    if (_092_) \mem[13] [3] <= _001_[3];
  always @(posedge clock)
    if (_092_) \mem[13] [4] <= _001_[4];
  always @(posedge clock)
    if (_092_) \mem[13] [5] <= _001_[5];
  always @(posedge clock)
    if (_092_) \mem[13] [6] <= _001_[6];
  always @(posedge clock)
    if (_092_) \mem[13] [7] <= _001_[7];
  always @(posedge clock)
    if (_092_) \mem[13] [8] <= _001_[8];
  always @(posedge clock)
    if (_091_) \mem[12] [0] <= _001_[0];
  always @(posedge clock)
    if (_091_) \mem[12] [1] <= _001_[1];
  always @(posedge clock)
    if (_091_) \mem[12] [2] <= _001_[2];
  always @(posedge clock)
    if (_091_) \mem[12] [3] <= _001_[3];
  always @(posedge clock)
    if (_091_) \mem[12] [4] <= _001_[4];
  always @(posedge clock)
    if (_091_) \mem[12] [5] <= _001_[5];
  always @(posedge clock)
    if (_091_) \mem[12] [6] <= _001_[6];
  always @(posedge clock)
    if (_091_) \mem[12] [7] <= _001_[7];
  always @(posedge clock)
    if (_091_) \mem[12] [8] <= _001_[8];
  always @(posedge clock)
    if (_090_) \mem[11] [0] <= _001_[0];
  always @(posedge clock)
    if (_090_) \mem[11] [1] <= _001_[1];
  always @(posedge clock)
    if (_090_) \mem[11] [2] <= _001_[2];
  always @(posedge clock)
    if (_090_) \mem[11] [3] <= _001_[3];
  always @(posedge clock)
    if (_090_) \mem[11] [4] <= _001_[4];
  always @(posedge clock)
    if (_090_) \mem[11] [5] <= _001_[5];
  always @(posedge clock)
    if (_090_) \mem[11] [6] <= _001_[6];
  always @(posedge clock)
    if (_090_) \mem[11] [7] <= _001_[7];
  always @(posedge clock)
    if (_090_) \mem[11] [8] <= _001_[8];
  always @(posedge clock)
    if (_089_) \mem[10] [0] <= _001_[0];
  always @(posedge clock)
    if (_089_) \mem[10] [1] <= _001_[1];
  always @(posedge clock)
    if (_089_) \mem[10] [2] <= _001_[2];
  always @(posedge clock)
    if (_089_) \mem[10] [3] <= _001_[3];
  always @(posedge clock)
    if (_089_) \mem[10] [4] <= _001_[4];
  always @(posedge clock)
    if (_089_) \mem[10] [5] <= _001_[5];
  always @(posedge clock)
    if (_089_) \mem[10] [6] <= _001_[6];
  always @(posedge clock)
    if (_089_) \mem[10] [7] <= _001_[7];
  always @(posedge clock)
    if (_089_) \mem[10] [8] <= _001_[8];
  always @(posedge clock)
    if (_103_) \mem[9] [0] <= _001_[0];
  always @(posedge clock)
    if (_103_) \mem[9] [1] <= _001_[1];
  always @(posedge clock)
    if (_103_) \mem[9] [2] <= _001_[2];
  always @(posedge clock)
    if (_103_) \mem[9] [3] <= _001_[3];
  always @(posedge clock)
    if (_103_) \mem[9] [4] <= _001_[4];
  always @(posedge clock)
    if (_103_) \mem[9] [5] <= _001_[5];
  always @(posedge clock)
    if (_103_) \mem[9] [6] <= _001_[6];
  always @(posedge clock)
    if (_103_) \mem[9] [7] <= _001_[7];
  always @(posedge clock)
    if (_103_) \mem[9] [8] <= _001_[8];
  always @(posedge clock)
    if (_102_) \mem[8] [0] <= _001_[0];
  always @(posedge clock)
    if (_102_) \mem[8] [1] <= _001_[1];
  always @(posedge clock)
    if (_102_) \mem[8] [2] <= _001_[2];
  always @(posedge clock)
    if (_102_) \mem[8] [3] <= _001_[3];
  always @(posedge clock)
    if (_102_) \mem[8] [4] <= _001_[4];
  always @(posedge clock)
    if (_102_) \mem[8] [5] <= _001_[5];
  always @(posedge clock)
    if (_102_) \mem[8] [6] <= _001_[6];
  always @(posedge clock)
    if (_102_) \mem[8] [7] <= _001_[7];
  always @(posedge clock)
    if (_102_) \mem[8] [8] <= _001_[8];
  always @(posedge clock)
    if (_101_) \mem[7] [0] <= _001_[0];
  always @(posedge clock)
    if (_101_) \mem[7] [1] <= _001_[1];
  always @(posedge clock)
    if (_101_) \mem[7] [2] <= _001_[2];
  always @(posedge clock)
    if (_101_) \mem[7] [3] <= _001_[3];
  always @(posedge clock)
    if (_101_) \mem[7] [4] <= _001_[4];
  always @(posedge clock)
    if (_101_) \mem[7] [5] <= _001_[5];
  always @(posedge clock)
    if (_101_) \mem[7] [6] <= _001_[6];
  always @(posedge clock)
    if (_101_) \mem[7] [7] <= _001_[7];
  always @(posedge clock)
    if (_101_) \mem[7] [8] <= _001_[8];
  always @(posedge clock)
    if (_100_) \mem[6] [0] <= _001_[0];
  always @(posedge clock)
    if (_100_) \mem[6] [1] <= _001_[1];
  always @(posedge clock)
    if (_100_) \mem[6] [2] <= _001_[2];
  always @(posedge clock)
    if (_100_) \mem[6] [3] <= _001_[3];
  always @(posedge clock)
    if (_100_) \mem[6] [4] <= _001_[4];
  always @(posedge clock)
    if (_100_) \mem[6] [5] <= _001_[5];
  always @(posedge clock)
    if (_100_) \mem[6] [6] <= _001_[6];
  always @(posedge clock)
    if (_100_) \mem[6] [7] <= _001_[7];
  always @(posedge clock)
    if (_100_) \mem[6] [8] <= _001_[8];
  always @(posedge clock)
    if (_099_) \mem[5] [0] <= _001_[0];
  always @(posedge clock)
    if (_099_) \mem[5] [1] <= _001_[1];
  always @(posedge clock)
    if (_099_) \mem[5] [2] <= _001_[2];
  always @(posedge clock)
    if (_099_) \mem[5] [3] <= _001_[3];
  always @(posedge clock)
    if (_099_) \mem[5] [4] <= _001_[4];
  always @(posedge clock)
    if (_099_) \mem[5] [5] <= _001_[5];
  always @(posedge clock)
    if (_099_) \mem[5] [6] <= _001_[6];
  always @(posedge clock)
    if (_099_) \mem[5] [7] <= _001_[7];
  always @(posedge clock)
    if (_099_) \mem[5] [8] <= _001_[8];
  always @(posedge clock)
    if (_098_) \mem[4] [0] <= _001_[0];
  always @(posedge clock)
    if (_098_) \mem[4] [1] <= _001_[1];
  always @(posedge clock)
    if (_098_) \mem[4] [2] <= _001_[2];
  always @(posedge clock)
    if (_098_) \mem[4] [3] <= _001_[3];
  always @(posedge clock)
    if (_098_) \mem[4] [4] <= _001_[4];
  always @(posedge clock)
    if (_098_) \mem[4] [5] <= _001_[5];
  always @(posedge clock)
    if (_098_) \mem[4] [6] <= _001_[6];
  always @(posedge clock)
    if (_098_) \mem[4] [7] <= _001_[7];
  always @(posedge clock)
    if (_098_) \mem[4] [8] <= _001_[8];
  always @(posedge clock)
    if (_097_) \mem[3] [0] <= _001_[0];
  always @(posedge clock)
    if (_097_) \mem[3] [1] <= _001_[1];
  always @(posedge clock)
    if (_097_) \mem[3] [2] <= _001_[2];
  always @(posedge clock)
    if (_097_) \mem[3] [3] <= _001_[3];
  always @(posedge clock)
    if (_097_) \mem[3] [4] <= _001_[4];
  always @(posedge clock)
    if (_097_) \mem[3] [5] <= _001_[5];
  always @(posedge clock)
    if (_097_) \mem[3] [6] <= _001_[6];
  always @(posedge clock)
    if (_097_) \mem[3] [7] <= _001_[7];
  always @(posedge clock)
    if (_097_) \mem[3] [8] <= _001_[8];
  always @(posedge clock)
    if (_096_) \mem[2] [0] <= _001_[0];
  always @(posedge clock)
    if (_096_) \mem[2] [1] <= _001_[1];
  always @(posedge clock)
    if (_096_) \mem[2] [2] <= _001_[2];
  always @(posedge clock)
    if (_096_) \mem[2] [3] <= _001_[3];
  always @(posedge clock)
    if (_096_) \mem[2] [4] <= _001_[4];
  always @(posedge clock)
    if (_096_) \mem[2] [5] <= _001_[5];
  always @(posedge clock)
    if (_096_) \mem[2] [6] <= _001_[6];
  always @(posedge clock)
    if (_096_) \mem[2] [7] <= _001_[7];
  always @(posedge clock)
    if (_096_) \mem[2] [8] <= _001_[8];
  always @(posedge clock)
    if (_095_) \mem[1] [0] <= _001_[0];
  always @(posedge clock)
    if (_095_) \mem[1] [1] <= _001_[1];
  always @(posedge clock)
    if (_095_) \mem[1] [2] <= _001_[2];
  always @(posedge clock)
    if (_095_) \mem[1] [3] <= _001_[3];
  always @(posedge clock)
    if (_095_) \mem[1] [4] <= _001_[4];
  always @(posedge clock)
    if (_095_) \mem[1] [5] <= _001_[5];
  always @(posedge clock)
    if (_095_) \mem[1] [6] <= _001_[6];
  always @(posedge clock)
    if (_095_) \mem[1] [7] <= _001_[7];
  always @(posedge clock)
    if (_095_) \mem[1] [8] <= _001_[8];
  always @(posedge clock)
    if (_088_) \mem[0] [0] <= _001_[0];
  always @(posedge clock)
    if (_088_) \mem[0] [1] <= _001_[1];
  always @(posedge clock)
    if (_088_) \mem[0] [2] <= _001_[2];
  always @(posedge clock)
    if (_088_) \mem[0] [3] <= _001_[3];
  always @(posedge clock)
    if (_088_) \mem[0] [4] <= _001_[4];
  always @(posedge clock)
    if (_088_) \mem[0] [5] <= _001_[5];
  always @(posedge clock)
    if (_088_) \mem[0] [6] <= _001_[6];
  always @(posedge clock)
    if (_088_) \mem[0] [7] <= _001_[7];
  always @(posedge clock)
    if (_088_) \mem[0] [8] <= _001_[8];
  always @(posedge clock)
    if (_046_) _009_[0] <= 1'h0;
    else _009_[0] <= _039_[0];
  always @(posedge clock)
    if (_046_) _009_[1] <= 1'h0;
    else _009_[1] <= _039_[1];
  always @(posedge clock)
    if (_046_) _009_[2] <= 1'h0;
    else _009_[2] <= _039_[2];
  always @(posedge clock)
    if (_046_) _009_[3] <= 1'h0;
    else _009_[3] <= _039_[3];
  always @(posedge clock)
    if (_046_) count[0] <= 1'h0;
    else if (_044_) count[0] <= _105_[0];
  always @(posedge clock)
    if (_046_) count[1] <= 1'h0;
    else if (_044_) count[1] <= _105_[1];
  always @(posedge clock)
    if (_046_) count[2] <= 1'h0;
    else if (_044_) count[2] <= _105_[2];
  always @(posedge clock)
    if (_046_) count[3] <= 1'h0;
    else if (_044_) count[3] <= _105_[3];
  always @(posedge clock)
    if (_046_) count[4] <= 1'h0;
    else if (_044_) count[4] <= _105_[4];
  always @(posedge clock)
    if (!resetn) data_out[0] <= 1'h0;
    else if (_043_) data_out[0] <= _111_[0];
  always @(posedge clock)
    if (!resetn) data_out[1] <= 1'h0;
    else if (_043_) data_out[1] <= _111_[1];
  always @(posedge clock)
    if (!resetn) data_out[2] <= 1'h0;
    else if (_043_) data_out[2] <= _111_[2];
  always @(posedge clock)
    if (!resetn) data_out[3] <= 1'h0;
    else if (_043_) data_out[3] <= _111_[3];
  always @(posedge clock)
    if (!resetn) data_out[4] <= 1'h0;
    else if (_043_) data_out[4] <= _111_[4];
  always @(posedge clock)
    if (!resetn) data_out[5] <= 1'h0;
    else if (_043_) data_out[5] <= _111_[5];
  always @(posedge clock)
    if (!resetn) data_out[6] <= 1'h0;
    else if (_043_) data_out[6] <= _111_[6];
  always @(posedge clock)
    if (!resetn) data_out[7] <= 1'h0;
    else if (_043_) data_out[7] <= _111_[7];
  always @(posedge clock)
    if (_046_) pl_count[0] <= 1'h0;
    else if (_045_) pl_count[0] <= _109_[0];
  always @(posedge clock)
    if (_046_) pl_count[1] <= 1'h0;
    else if (_045_) pl_count[1] <= _109_[1];
  always @(posedge clock)
    if (_046_) pl_count[2] <= 1'h0;
    else if (_045_) pl_count[2] <= _109_[2];
  always @(posedge clock)
    if (_046_) pl_count[3] <= 1'h0;
    else if (_045_) pl_count[3] <= _109_[3];
  always @(posedge clock)
    if (_046_) pl_count[4] <= 1'h0;
    else if (_045_) pl_count[4] <= _109_[4];
  always @(posedge clock)
    if (_046_) pl_count[5] <= 1'h0;
    else if (_045_) pl_count[5] <= _109_[5];
  always @(posedge clock)
    if (_046_) wrt_ptr[0] <= 1'h0;
    else if (_008_[0]) wrt_ptr[0] <= _116_[0];
  always @(posedge clock)
    if (_046_) wrt_ptr[1] <= 1'h0;
    else if (_008_[0]) wrt_ptr[1] <= _117_[1];
  always @(posedge clock)
    if (_046_) wrt_ptr[2] <= 1'h0;
    else if (_008_[0]) wrt_ptr[2] <= _117_[2];
  always @(posedge clock)
    if (_046_) wrt_ptr[3] <= 1'h0;
    else if (_008_[0]) wrt_ptr[3] <= _117_[3];
  always @(posedge clock)
    if (_046_) rd_ptr[0] <= 1'h0;
    else if (_059_[0]) rd_ptr[0] <= _119_[0];
  always @(posedge clock)
    if (_046_) rd_ptr[1] <= 1'h0;
    else if (_059_[0]) rd_ptr[1] <= _120_[1];
  always @(posedge clock)
    if (_046_) rd_ptr[2] <= 1'h0;
    else if (_059_[0]) rd_ptr[2] <= _120_[2];
  always @(posedge clock)
    if (_046_) rd_ptr[3] <= 1'h0;
    else if (_059_[0]) rd_ptr[3] <= _120_[3];
  assign _126_[4] = ~count[4];
  assign _129_[1] = ~pl_count[1];
  assign _129_[2] = ~pl_count[2];
  assign _129_[3] = ~pl_count[3];
  assign _129_[5] = ~pl_count[5];
  assign _129_[4] = ~pl_count[4];
  assign _116_[0] = ~wrt_ptr[0];
  assign _130_[0] = ~pl_count[0];
  assign _040_ = ~_008_[0];
  assign _041_ = ~_059_[0];
  assign _034_ = _018_ & _030_;
  assign _033_ = _016_ & _030_;
  assign _032_ = _014_ & _030_;
  assign _031_ = _011_ & _030_;
  assign _030_ = _000_[2] & _000_[3];
  assign _029_ = _018_ & _025_;
  assign _028_ = _016_ & _025_;
  assign _027_ = _014_ & _025_;
  assign _026_ = _011_ & _025_;
  assign _025_ = _037_ & _000_[3];
  assign _024_ = _018_ & _020_;
  assign _023_ = _016_ & _020_;
  assign _022_ = _014_ & _020_;
  assign _021_ = _011_ & _020_;
  assign _020_ = _000_[2] & _038_;
  assign _019_ = _018_ & _012_;
  assign _018_ = _000_[0] & _000_[1];
  assign _017_ = _016_ & _012_;
  assign _016_ = _035_ & _000_[1];
  assign _015_ = _014_ & _012_;
  assign _014_ = _000_[0] & _036_;
  assign _013_ = _011_ & _012_;
  assign _012_ = _037_ & _038_;
  assign _011_ = _035_ & _036_;
  assign _094_ = _034_ & _002_[0];
  assign _093_ = _033_ & _002_[0];
  assign _092_ = _032_ & _002_[0];
  assign _091_ = _031_ & _002_[0];
  assign _090_ = _029_ & _002_[0];
  assign _089_ = _028_ & _002_[0];
  assign _103_ = _027_ & _002_[0];
  assign _102_ = _026_ & _002_[0];
  assign _101_ = _024_ & _002_[0];
  assign _100_ = _023_ & _002_[0];
  assign _099_ = _022_ & _002_[0];
  assign _098_ = _021_ & _002_[0];
  assign _097_ = _019_ & _002_[0];
  assign _096_ = _017_ & _002_[0];
  assign _095_ = _015_ & _002_[0];
  assign _088_ = _013_ & _002_[0];
  assign _117_[1] = wrt_ptr[1] ^ wrt_ptr[0];
  assign _117_[2] = wrt_ptr[2] ^ _115_[1];
  assign _117_[3] = wrt_ptr[3] ^ _115_[2];
  assign _120_[1] = rd_ptr[1] ^ rd_ptr[0];
  assign _120_[2] = rd_ptr[2] ^ _118_[1];
  assign _120_[3] = rd_ptr[3] ^ _118_[2];
  assign _124_[1] = _121_[1] ^ _121_[0];
  assign _124_[2] = _121_[2] ^ _122_[1];
  assign _124_[3] = _121_[3] ^ _122_[2];
  assign _124_[4] = _121_[4] ^ _122_[3];
  assign _124_[5] = _121_[5] ^ _122_[4];
  assign _130_[1] = _129_[1] ^ pl_count[0];
  assign _130_[2] = _129_[2] ^ _128_[1];
  assign _130_[3] = _129_[3] ^ _128_[2];
  assign _130_[4] = _129_[4] ^ _128_[3];
  assign _130_[5] = _129_[5] ^ _128_[4];
  assign _114_[1] = count[1] ^ count[0];
  assign _114_[2] = count[2] ^ _112_[1];
  assign _114_[3] = count[3] ^ _112_[2];
  assign _114_[4] = count[4] ^ _112_[3];
  assign _127_[1] = _126_[1] ^ count[0];
  assign _127_[2] = _126_[2] ^ _125_[1];
  assign _127_[3] = _126_[3] ^ _125_[2];
  assign _127_[4] = _126_[4] ^ _125_[3];
  assign _115_[2] = wrt_ptr[2] & _115_[1];
  assign _115_[1] = wrt_ptr[1] & wrt_ptr[0];
  assign _118_[2] = rd_ptr[2] & _118_[1];
  assign _118_[1] = rd_ptr[1] & rd_ptr[0];
  assign _122_[2] = _121_[2] & _122_[1];
  assign _122_[4] = _121_[4] & _122_[3];
  assign _122_[3] = _132_ & _122_[1];
  assign _132_ = _121_[3] & _121_[2];
  assign _122_[1] = _121_[1] & _121_[0];
  assign _143_ = _129_[2] & _128_[1];
  assign _144_ = _129_[4] & _128_[3];
  assign _128_[4] = pl_count[4] | _144_;
  assign _128_[3] = _145_ | _141_;
  assign _141_ = _142_ & _128_[1];
  assign _142_ = _129_[3] & _129_[2];
  assign _145_ = pl_count[3] | _140_;
  assign _140_ = _129_[3] & pl_count[2];
  assign _128_[2] = pl_count[2] | _143_;
  assign _128_[1] = pl_count[1] | _139_;
  assign _139_ = _129_[1] & pl_count[0];
  assign _112_[2] = count[2] & _112_[1];
  assign _112_[3] = _131_ & _112_[1];
  assign _131_ = count[3] & count[2];
  assign _112_[1] = count[1] & count[0];
  assign _125_[2] = count[2] | _137_;
  assign _137_ = _126_[2] & _125_[1];
  assign _125_[3] = _138_ | _135_;
  assign _135_ = _136_ & _125_[1];
  assign _136_ = _126_[3] & _126_[2];
  assign _138_ = count[3] | _134_;
  assign _134_ = _126_[3] & count[2];
  assign _125_[1] = count[1] | _133_;
  assign _133_ = _126_[1] & count[0];
  assign _047_ = soft_reset | _073_;
  assign _043_ = _047_ | _059_[0];
  assign _045_ = _042_ & _059_[0];
  assign _042_ = _104_[8] | _053_;
  assign _046_ = _010_ | soft_reset;
  assign _048_[0] = count[0] | count[1];
  assign _048_[1] = count[2] | count[3];
  assign _049_ = _048_[0] | _048_[1];
  assign _060_ = _049_ | _126_[4];
  assign _061_ = _041_ | _008_[0];
  assign _062_ = _059_[0] | _040_;
  assign _052_ = _049_ | count[4];
  assign _050_[0] = pl_count[0] | pl_count[1];
  assign _050_[1] = pl_count[2] | pl_count[3];
  assign _050_[2] = pl_count[4] | pl_count[5];
  assign _051_ = _050_[0] | _050_[1];
  assign _053_ = _051_ | _050_[2];
  assign _044_ = _106_ | _107_;
  assign _054_ = _063_ | _064_;
  assign _055_ = _065_ | _066_;
  assign _056_ = _067_ | _068_;
  assign _057_ = _069_ | _070_;
  assign _058_ = _071_ | _072_;
  assign empty = ~_052_;
  assign full = ~_060_;
  assign _073_ = ~_053_;
  assign _106_ = ~_061_;
  assign _107_ = ~_062_;
  assign _059_[0] = read_enb & _052_;
  assign _008_[0] = write_enb & _060_;
  assign _039_[0] = _059_[0] ? _119_[0] : rd_ptr[0];
  assign _039_[1] = _059_[0] ? _120_[1] : rd_ptr[1];
  assign _039_[2] = _059_[0] ? _120_[2] : rd_ptr[2];
  assign _039_[3] = _059_[0] ? _120_[3] : rd_ptr[3];
  assign _087_[0] = _009_[0] ? \mem[15] [0] : \mem[14] [0];
  assign _087_[1] = _009_[0] ? \mem[15] [1] : \mem[14] [1];
  assign _087_[2] = _009_[0] ? \mem[15] [2] : \mem[14] [2];
  assign _087_[3] = _009_[0] ? \mem[15] [3] : \mem[14] [3];
  assign _087_[4] = _009_[0] ? \mem[15] [4] : \mem[14] [4];
  assign _087_[5] = _009_[0] ? \mem[15] [5] : \mem[14] [5];
  assign _087_[6] = _009_[0] ? \mem[15] [6] : \mem[14] [6];
  assign _087_[7] = _009_[0] ? \mem[15] [7] : \mem[14] [7];
  assign _087_[8] = _009_[0] ? \mem[15] [8] : \mem[14] [8];
  assign _086_[0] = _009_[0] ? \mem[13] [0] : \mem[12] [0];
  assign _086_[1] = _009_[0] ? \mem[13] [1] : \mem[12] [1];
  assign _086_[2] = _009_[0] ? \mem[13] [2] : \mem[12] [2];
  assign _086_[3] = _009_[0] ? \mem[13] [3] : \mem[12] [3];
  assign _086_[4] = _009_[0] ? \mem[13] [4] : \mem[12] [4];
  assign _086_[5] = _009_[0] ? \mem[13] [5] : \mem[12] [5];
  assign _086_[6] = _009_[0] ? \mem[13] [6] : \mem[12] [6];
  assign _086_[7] = _009_[0] ? \mem[13] [7] : \mem[12] [7];
  assign _086_[8] = _009_[0] ? \mem[13] [8] : \mem[12] [8];
  assign _085_[0] = _009_[0] ? \mem[11] [0] : \mem[10] [0];
  assign _085_[1] = _009_[0] ? \mem[11] [1] : \mem[10] [1];
  assign _085_[2] = _009_[0] ? \mem[11] [2] : \mem[10] [2];
  assign _085_[3] = _009_[0] ? \mem[11] [3] : \mem[10] [3];
  assign _085_[4] = _009_[0] ? \mem[11] [4] : \mem[10] [4];
  assign _085_[5] = _009_[0] ? \mem[11] [5] : \mem[10] [5];
  assign _085_[6] = _009_[0] ? \mem[11] [6] : \mem[10] [6];
  assign _085_[7] = _009_[0] ? \mem[11] [7] : \mem[10] [7];
  assign _085_[8] = _009_[0] ? \mem[11] [8] : \mem[10] [8];
  assign _084_[0] = _009_[0] ? \mem[9] [0] : \mem[8] [0];
  assign _084_[1] = _009_[0] ? \mem[9] [1] : \mem[8] [1];
  assign _084_[2] = _009_[0] ? \mem[9] [2] : \mem[8] [2];
  assign _084_[3] = _009_[0] ? \mem[9] [3] : \mem[8] [3];
  assign _084_[4] = _009_[0] ? \mem[9] [4] : \mem[8] [4];
  assign _084_[5] = _009_[0] ? \mem[9] [5] : \mem[8] [5];
  assign _084_[6] = _009_[0] ? \mem[9] [6] : \mem[8] [6];
  assign _084_[7] = _009_[0] ? \mem[9] [7] : \mem[8] [7];
  assign _084_[8] = _009_[0] ? \mem[9] [8] : \mem[8] [8];
  assign _108_[0] = _053_ ? _130_[0] : 1'hx;
  assign _108_[1] = _053_ ? _130_[1] : 1'hx;
  assign _108_[2] = _053_ ? _130_[2] : 1'hx;
  assign _108_[3] = _053_ ? _130_[3] : 1'hx;
  assign _108_[4] = _053_ ? _130_[4] : 1'hx;
  assign _108_[5] = _053_ ? _130_[5] : 1'hx;
  assign _109_[0] = _104_[8] ? _123_[0] : _108_[0];
  assign _109_[1] = _104_[8] ? _124_[1] : _108_[1];
  assign _109_[2] = _104_[8] ? _124_[2] : _108_[2];
  assign _109_[3] = _104_[8] ? _124_[3] : _108_[3];
  assign _109_[4] = _104_[8] ? _124_[4] : _108_[4];
  assign _109_[5] = _104_[8] ? _124_[5] : _108_[5];
  assign _083_[0] = _009_[0] ? \mem[7] [0] : \mem[6] [0];
  assign _083_[1] = _009_[0] ? \mem[7] [1] : \mem[6] [1];
  assign _083_[2] = _009_[0] ? \mem[7] [2] : \mem[6] [2];
  assign _083_[3] = _009_[0] ? \mem[7] [3] : \mem[6] [3];
  assign _083_[4] = _009_[0] ? \mem[7] [4] : \mem[6] [4];
  assign _083_[5] = _009_[0] ? \mem[7] [5] : \mem[6] [5];
  assign _083_[6] = _009_[0] ? \mem[7] [6] : \mem[6] [6];
  assign _083_[7] = _009_[0] ? \mem[7] [7] : \mem[6] [7];
  assign _083_[8] = _009_[0] ? \mem[7] [8] : \mem[6] [8];
  assign _082_[0] = _009_[0] ? \mem[5] [0] : \mem[4] [0];
  assign _082_[1] = _009_[0] ? \mem[5] [1] : \mem[4] [1];
  assign _082_[2] = _009_[0] ? \mem[5] [2] : \mem[4] [2];
  assign _082_[3] = _009_[0] ? \mem[5] [3] : \mem[4] [3];
  assign _082_[4] = _009_[0] ? \mem[5] [4] : \mem[4] [4];
  assign _082_[5] = _009_[0] ? \mem[5] [5] : \mem[4] [5];
  assign _082_[6] = _009_[0] ? \mem[5] [6] : \mem[4] [6];
  assign _082_[7] = _009_[0] ? \mem[5] [7] : \mem[4] [7];
  assign _082_[8] = _009_[0] ? \mem[5] [8] : \mem[4] [8];
  assign _081_[0] = _009_[0] ? \mem[3] [0] : \mem[2] [0];
  assign _081_[1] = _009_[0] ? \mem[3] [1] : \mem[2] [1];
  assign _081_[2] = _009_[0] ? \mem[3] [2] : \mem[2] [2];
  assign _081_[3] = _009_[0] ? \mem[3] [3] : \mem[2] [3];
  assign _081_[4] = _009_[0] ? \mem[3] [4] : \mem[2] [4];
  assign _081_[5] = _009_[0] ? \mem[3] [5] : \mem[2] [5];
  assign _081_[6] = _009_[0] ? \mem[3] [6] : \mem[2] [6];
  assign _081_[7] = _009_[0] ? \mem[3] [7] : \mem[2] [7];
  assign _081_[8] = _009_[0] ? \mem[3] [8] : \mem[2] [8];
  assign _080_[0] = _009_[0] ? \mem[1] [0] : \mem[0] [0];
  assign _080_[1] = _009_[0] ? \mem[1] [1] : \mem[0] [1];
  assign _080_[2] = _009_[0] ? \mem[1] [2] : \mem[0] [2];
  assign _080_[3] = _009_[0] ? \mem[1] [3] : \mem[0] [3];
  assign _080_[4] = _009_[0] ? \mem[1] [4] : \mem[0] [4];
  assign _080_[5] = _009_[0] ? \mem[1] [5] : \mem[0] [5];
  assign _080_[6] = _009_[0] ? \mem[1] [6] : \mem[0] [6];
  assign _080_[7] = _009_[0] ? \mem[1] [7] : \mem[0] [7];
  assign _080_[8] = _009_[0] ? \mem[1] [8] : \mem[0] [8];
  assign _079_[0] = _009_[1] ? _087_[0] : _086_[0];
  assign _079_[1] = _009_[1] ? _087_[1] : _086_[1];
  assign _079_[2] = _009_[1] ? _087_[2] : _086_[2];
  assign _079_[3] = _009_[1] ? _087_[3] : _086_[3];
  assign _079_[4] = _009_[1] ? _087_[4] : _086_[4];
  assign _079_[5] = _009_[1] ? _087_[5] : _086_[5];
  assign _079_[6] = _009_[1] ? _087_[6] : _086_[6];
  assign _079_[7] = _009_[1] ? _087_[7] : _086_[7];
  assign _079_[8] = _009_[1] ? _087_[8] : _086_[8];
  assign _078_[0] = _009_[1] ? _085_[0] : _084_[0];
  assign _078_[1] = _009_[1] ? _085_[1] : _084_[1];
  assign _078_[2] = _009_[1] ? _085_[2] : _084_[2];
  assign _078_[3] = _009_[1] ? _085_[3] : _084_[3];
  assign _078_[4] = _009_[1] ? _085_[4] : _084_[4];
  assign _078_[5] = _009_[1] ? _085_[5] : _084_[5];
  assign _078_[6] = _009_[1] ? _085_[6] : _084_[6];
  assign _078_[7] = _009_[1] ? _085_[7] : _084_[7];
  assign _078_[8] = _009_[1] ? _085_[8] : _084_[8];
  assign _077_[0] = _009_[1] ? _083_[0] : _082_[0];
  assign _077_[1] = _009_[1] ? _083_[1] : _082_[1];
  assign _077_[2] = _009_[1] ? _083_[2] : _082_[2];
  assign _077_[3] = _009_[1] ? _083_[3] : _082_[3];
  assign _077_[4] = _009_[1] ? _083_[4] : _082_[4];
  assign _077_[5] = _009_[1] ? _083_[5] : _082_[5];
  assign _077_[6] = _009_[1] ? _083_[6] : _082_[6];
  assign _077_[7] = _009_[1] ? _083_[7] : _082_[7];
  assign _077_[8] = _009_[1] ? _083_[8] : _082_[8];
  assign _110_[0] = _059_[0] ? _104_[0] : 1'hx;
  assign _110_[1] = _059_[0] ? _104_[1] : 1'hx;
  assign _110_[2] = _059_[0] ? _121_[0] : 1'hx;
  assign _110_[3] = _059_[0] ? _121_[1] : 1'hx;
  assign _110_[4] = _059_[0] ? _121_[2] : 1'hx;
  assign _110_[5] = _059_[0] ? _121_[3] : 1'hx;
  assign _110_[6] = _059_[0] ? _121_[4] : 1'hx;
  assign _110_[7] = _059_[0] ? _121_[5] : 1'hx;
  assign _111_[0] = soft_reset ? 1'hz : _110_[0];
  assign _111_[1] = soft_reset ? 1'hz : _110_[1];
  assign _111_[2] = soft_reset ? 1'hz : _110_[2];
  assign _111_[3] = soft_reset ? 1'hz : _110_[3];
  assign _111_[4] = soft_reset ? 1'hz : _110_[4];
  assign _111_[5] = soft_reset ? 1'hz : _110_[5];
  assign _111_[6] = soft_reset ? 1'hz : _110_[6];
  assign _111_[7] = soft_reset ? 1'hz : _110_[7];
  assign _076_[0] = _009_[1] ? _081_[0] : _080_[0];
  assign _076_[1] = _009_[1] ? _081_[1] : _080_[1];
  assign _076_[2] = _009_[1] ? _081_[2] : _080_[2];
  assign _076_[3] = _009_[1] ? _081_[3] : _080_[3];
  assign _076_[4] = _009_[1] ? _081_[4] : _080_[4];
  assign _076_[5] = _009_[1] ? _081_[5] : _080_[5];
  assign _076_[6] = _009_[1] ? _081_[6] : _080_[6];
  assign _076_[7] = _009_[1] ? _081_[7] : _080_[7];
  assign _076_[8] = _009_[1] ? _081_[8] : _080_[8];
  assign _075_[0] = _009_[2] ? _079_[0] : _078_[0];
  assign _075_[1] = _009_[2] ? _079_[1] : _078_[1];
  assign _075_[2] = _009_[2] ? _079_[2] : _078_[2];
  assign _075_[3] = _009_[2] ? _079_[3] : _078_[3];
  assign _075_[4] = _009_[2] ? _079_[4] : _078_[4];
  assign _075_[5] = _009_[2] ? _079_[5] : _078_[5];
  assign _075_[6] = _009_[2] ? _079_[6] : _078_[6];
  assign _075_[7] = _009_[2] ? _079_[7] : _078_[7];
  assign _075_[8] = _009_[2] ? _079_[8] : _078_[8];
  assign _074_[0] = _009_[2] ? _077_[0] : _076_[0];
  assign _074_[1] = _009_[2] ? _077_[1] : _076_[1];
  assign _074_[2] = _009_[2] ? _077_[2] : _076_[2];
  assign _074_[3] = _009_[2] ? _077_[3] : _076_[3];
  assign _074_[4] = _009_[2] ? _077_[4] : _076_[4];
  assign _074_[5] = _009_[2] ? _077_[5] : _076_[5];
  assign _074_[6] = _009_[2] ? _077_[6] : _076_[6];
  assign _074_[7] = _009_[2] ? _077_[7] : _076_[7];
  assign _074_[8] = _009_[2] ? _077_[8] : _076_[8];
  assign _104_[0] = _009_[3] ? _075_[0] : _074_[0];
  assign _104_[1] = _009_[3] ? _075_[1] : _074_[1];
  assign _121_[0] = _009_[3] ? _075_[2] : _074_[2];
  assign _121_[1] = _009_[3] ? _075_[3] : _074_[3];
  assign _121_[2] = _009_[3] ? _075_[4] : _074_[4];
  assign _121_[3] = _009_[3] ? _075_[5] : _074_[5];
  assign _121_[4] = _009_[3] ? _075_[6] : _074_[6];
  assign _121_[5] = _009_[3] ? _075_[7] : _074_[7];
  assign _104_[8] = _009_[3] ? _075_[8] : _074_[8];
  assign _007_[0] = _008_[0] ? data_in[0] : 1'hx;
  assign _007_[1] = _008_[0] ? data_in[1] : 1'hx;
  assign _007_[2] = _008_[0] ? data_in[2] : 1'hx;
  assign _007_[3] = _008_[0] ? data_in[3] : 1'hx;
  assign _007_[4] = _008_[0] ? data_in[4] : 1'hx;
  assign _007_[5] = _008_[0] ? data_in[5] : 1'hx;
  assign _007_[6] = _008_[0] ? data_in[6] : 1'hx;
  assign _007_[7] = _008_[0] ? data_in[7] : 1'hx;
  assign _007_[8] = _008_[0] ? lfd_state : 1'hx;
  assign _006_[0] = _008_[0] ? wrt_ptr[0] : 1'hx;
  assign _006_[1] = _008_[0] ? wrt_ptr[1] : 1'hx;
  assign _006_[2] = _008_[0] ? wrt_ptr[2] : 1'hx;
  assign _006_[3] = _008_[0] ? wrt_ptr[3] : 1'hx;
  assign _005_[0] = soft_reset ? 1'h0 : _008_[0];
  assign _004_[0] = soft_reset ? 1'hx : _007_[0];
  assign _004_[1] = soft_reset ? 1'hx : _007_[1];
  assign _004_[2] = soft_reset ? 1'hx : _007_[2];
  assign _004_[3] = soft_reset ? 1'hx : _007_[3];
  assign _004_[4] = soft_reset ? 1'hx : _007_[4];
  assign _004_[5] = soft_reset ? 1'hx : _007_[5];
  assign _004_[6] = soft_reset ? 1'hx : _007_[6];
  assign _004_[7] = soft_reset ? 1'hx : _007_[7];
  assign _004_[8] = soft_reset ? 1'hx : _007_[8];
  assign _003_[0] = soft_reset ? 1'hx : _006_[0];
  assign _003_[1] = soft_reset ? 1'hx : _006_[1];
  assign _003_[2] = soft_reset ? 1'hx : _006_[2];
  assign _003_[3] = soft_reset ? 1'hx : _006_[3];
  assign _002_[0] = resetn ? _005_[0] : 1'h0;
  assign _001_[0] = resetn ? _004_[0] : 1'hx;
  assign _001_[1] = resetn ? _004_[1] : 1'hx;
  assign _001_[2] = resetn ? _004_[2] : 1'hx;
  assign _001_[3] = resetn ? _004_[3] : 1'hx;
  assign _001_[4] = resetn ? _004_[4] : 1'hx;
  assign _001_[5] = resetn ? _004_[5] : 1'hx;
  assign _001_[6] = resetn ? _004_[6] : 1'hx;
  assign _001_[7] = resetn ? _004_[7] : 1'hx;
  assign _001_[8] = resetn ? _004_[8] : 1'hx;
  assign _000_[0] = resetn ? _003_[0] : 1'hx;
  assign _000_[1] = resetn ? _003_[1] : 1'hx;
  assign _000_[2] = resetn ? _003_[2] : 1'hx;
  assign _000_[3] = resetn ? _003_[3] : 1'hx;
  assign _063_ = _113_[0] & _106_;
  assign _064_ = _113_[0] & _107_;
  assign _065_ = _127_[1] & _106_;
  assign _066_ = _114_[1] & _107_;
  assign _067_ = _127_[2] & _106_;
  assign _068_ = _114_[2] & _107_;
  assign _069_ = _127_[3] & _106_;
  assign _070_ = _114_[3] & _107_;
  assign _071_ = _127_[4] & _106_;
  assign _072_ = _114_[4] & _107_;
  assign _038_ = ~_000_[3];
  assign _037_ = ~_000_[2];
  assign _036_ = ~_000_[1];
  assign _035_ = ~_000_[0];
  assign _010_ = ~resetn;
  assign _119_[0] = ~rd_ptr[0];
  assign _123_[0] = ~_121_[0];
  assign _113_[0] = ~count[0];
  assign _126_[1] = ~count[1];
  assign _126_[2] = ~count[2];
  assign _126_[3] = ~count[3];
  assign _105_[0] = _044_ ? _054_ : 1'hx;
  assign _105_[1] = _044_ ? _055_ : 1'hx;
  assign _105_[2] = _044_ ? _056_ : 1'hx;
  assign _105_[3] = _044_ ? _057_ : 1'hx;
  assign _105_[4] = _044_ ? _058_ : 1'hx;
  assign _113_[4:1] = count[4:1];
  assign _128_[0] = pl_count[0];
  assign _120_[0] = _119_[0];
  assign _129_[0] = pl_count[0];
  assign _116_[3:1] = wrt_ptr[3:1];
  assign _127_[0] = _113_[0];
  assign _123_[5:1] = _121_[5:1];
  assign _125_[0] = count[0];
  assign _119_[3:1] = rd_ptr[3:1];
  assign _124_[0] = _123_[0];
  assign _126_[0] = count[0];
  assign _117_[0] = _116_[0];
  assign _114_[0] = _113_[0];
  assign _118_[0] = rd_ptr[0];
  assign _122_[0] = _121_[0];
  assign _112_[0] = count[0];
  assign _059_[1] = _040_;
  assign _115_[0] = wrt_ptr[0];
  assign _008_[8:1] = { _008_[0], _008_[0], _008_[0], _008_[0], _008_[0], _008_[0], _008_[0], _008_[0] };
  assign _104_[7:2] = _121_;
  assign _005_[8:1] = { _005_[0], _005_[0], _005_[0], _005_[0], _005_[0], _005_[0], _005_[0], _005_[0] };
  assign _002_[8:1] = { _002_[0], _002_[0], _002_[0], _002_[0], _002_[0], _002_[0], _002_[0], _002_[0] };
endmodule

module router_fsm(clock, resetn, pkt_valid, parity_done, fifo_full, low_pkt_valid, soft_reset_0, soft_reset_1, soft_reset_2, fifo_empty_0, fifo_empty_1, fifo_empty_2, data_in, busy, detect_add, ld_state, laf_state, full_state, write_enb_reg, rst_int_reg, lfd_state
);
  input clock;
  wire clock;
  input resetn;
  wire resetn;
  input pkt_valid;
  wire pkt_valid;
  input parity_done;
  wire parity_done;
  input fifo_full;
  wire fifo_full;
  input low_pkt_valid;
  wire low_pkt_valid;
  input soft_reset_0;
  wire soft_reset_0;
  input soft_reset_1;
  wire soft_reset_1;
  input soft_reset_2;
  wire soft_reset_2;
  input fifo_empty_0;
  wire fifo_empty_0;
  input fifo_empty_1;
  wire fifo_empty_1;
  input fifo_empty_2;
  wire fifo_empty_2;
  input [1:0] data_in;
  wire [1:0] data_in;
  output busy;
  reg busy;
  output detect_add;
  reg detect_add;
  output ld_state;
  reg ld_state;
  output laf_state;
  reg laf_state;
  output full_state;
  reg full_state;
  output write_enb_reg;
  reg write_enb_reg;
  output rst_int_reg;
  reg rst_int_reg;
  output lfd_state;
  reg lfd_state;
  wire [7:0] _000_;
  wire [2:0] _001_;
  wire [2:0] _002_;
  wire [2:0] _003_;
  wire [2:0] _004_;
  wire [2:0] _005_;
  wire [2:0] _006_;
  wire [2:0] _007_;
  wire [2:0] _008_;
  wire [2:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire [3:0] _023_;
  wire [1:0] _024_;
  wire _025_;
  wire [3:0] _026_;
  wire [1:0] _027_;
  wire _028_;
  wire [3:0] _029_;
  wire [1:0] _030_;
  wire _031_;
  wire [3:0] _032_;
  wire [1:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire [7:0] _083_;
  wire [7:0] _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire [2:0] next_state;
  reg [2:0] pre_state;
  always @(posedge clock)
    if (_080_) pre_state[0] <= 1'h0;
    else pre_state[0] <= next_state[0];
  always @(posedge clock)
    if (_080_) pre_state[1] <= 1'h0;
    else pre_state[1] <= next_state[1];
  always @(posedge clock)
    if (_080_) pre_state[2] <= 1'h0;
    else pre_state[2] <= next_state[2];
  always @(posedge clock)
    write_enb_reg <= _000_[5];
  always @(posedge clock)
    if (_009_[2]) detect_add <= 1'h0;
    else detect_add <= _083_[7];
  always @(posedge clock)
    if (!_016_) rst_int_reg <= 1'h0;
    else rst_int_reg <= _009_[0];
  always @(posedge clock)
    if (_017_) ld_state <= 1'h0;
    else ld_state <= _084_[7];
  always @(posedge clock)
    if (!_009_[2]) full_state <= 1'h0;
    else full_state <= _083_[7];
  always @(posedge clock)
    if (!_009_[2]) laf_state <= 1'h0;
    else laf_state <= _083_[0];
  always @(posedge clock)
    if (_009_[2]) busy <= 1'h1;
    else busy <= _009_[0];
  always @(posedge clock)
    if (_009_[2]) lfd_state <= 1'h0;
    else lfd_state <= _083_[0];
  assign _010_ = ~data_in[1];
  assign _011_ = ~data_in[0];
  assign _014_ = ~pre_state[2];
  assign _013_ = ~pre_state[1];
  assign _012_ = ~pre_state[0];
  assign _015_ = ~_009_[1];
  assign _036_ = _011_ | data_in[1];
  assign _037_ = data_in[0] | _010_;
  assign _018_ = pre_state[0] | _013_;
  assign _038_ = _018_ | _014_;
  assign _019_ = _012_ | _013_;
  assign _039_ = _019_ | _014_;
  assign _040_ = _019_ | pre_state[2];
  assign _041_ = _020_ | _014_;
  assign _021_ = pre_state[0] | pre_state[1];
  assign _042_ = _021_ | _014_;
  assign _043_ = _018_ | pre_state[2];
  assign _020_ = _012_ | pre_state[1];
  assign _044_ = _020_ | pre_state[2];
  assign _016_ = _009_[1] & _009_[2];
  assign _017_ = _015_ | _009_[2];
  assign _022_ = data_in[0] | data_in[1];
  assign _023_[0] = _085_ | _086_;
  assign _023_[1] = _045_ | _087_;
  assign _023_[2] = _053_ | _088_;
  assign _023_[3] = _050_ | _089_;
  assign _024_[0] = _023_[0] | _023_[1];
  assign _024_[1] = _023_[2] | _023_[3];
  assign _025_ = _024_[0] | _024_[1];
  assign _026_[1] = _045_ | _046_;
  assign _026_[2] = _047_ | _048_;
  assign _027_[0] = _026_[0] | _026_[1];
  assign _027_[1] = _026_[2] | _026_[3];
  assign _028_ = _027_[0] | _027_[1];
  assign _029_[1] = _045_ | _049_;
  assign _029_[3] = _050_ | _032_[3];
  assign _030_[0] = _029_[0] | _029_[1];
  assign _030_[1] = _029_[2] | _029_[3];
  assign _031_ = _030_[0] | _030_[1];
  assign _032_[0] = _029_[0] | _051_;
  assign _032_[1] = _045_ | _052_;
  assign _032_[2] = _053_ | _054_;
  assign _033_[0] = _032_[0] | _032_[1];
  assign _033_[1] = _032_[2] | _032_[3];
  assign _034_ = _033_[0] | _033_[1];
  assign _035_ = _021_ | pre_state[2];
  assign _071_ = ~resetn;
  assign _072_ = ~fifo_empty_0;
  assign _073_ = ~fifo_empty_1;
  assign _074_ = ~fifo_empty_2;
  assign _075_ = ~pkt_valid;
  assign _076_ = ~low_pkt_valid;
  assign _055_ = ~_022_;
  assign _056_ = ~_036_;
  assign _057_ = ~_037_;
  assign _085_ = ~_038_;
  assign _086_ = ~_039_;
  assign _045_ = ~_040_;
  assign _087_ = ~_041_;
  assign _053_ = ~_042_;
  assign _088_ = ~_043_;
  assign _050_ = ~_044_;
  assign _089_ = ~_035_;
  assign _078_ = _071_ | soft_reset_0;
  assign _079_ = _078_ | soft_reset_1;
  assign _080_ = _079_ | soft_reset_2;
  assign _062_ = _061_ & fifo_empty_0;
  assign _064_ = _063_ & fifo_empty_1;
  assign _081_ = _062_ | _064_;
  assign _066_ = _065_ & fifo_empty_2;
  assign _002_[0] = _081_ | _066_;
  assign _061_ = pkt_valid & _055_;
  assign _067_ = _061_ & _072_;
  assign _063_ = pkt_valid & _056_;
  assign _068_ = _063_ & _073_;
  assign _082_ = _067_ | _068_;
  assign _065_ = pkt_valid & _057_;
  assign _069_ = _065_ & _074_;
  assign _003_[1] = _082_ | _069_;
  assign _005_[0] = _004_[1] & _075_;
  assign _070_ = _008_[0] & low_pkt_valid;
  assign _007_[1] = _008_[0] & _076_;
  assign _058_ = fifo_empty_0 & _055_;
  assign _059_ = fifo_empty_1 & _056_;
  assign _077_ = _058_ | _059_;
  assign _060_ = fifo_empty_2 & _057_;
  assign _001_[0] = _077_ | _060_;
  assign _009_[0] = _080_ ? 1'h0 : next_state[0];
  assign _009_[1] = _080_ ? 1'h0 : next_state[1];
  assign _009_[2] = _080_ ? 1'h0 : next_state[2];
  assign _001_[1] = ~_001_[0];
  assign _008_[0] = ~parity_done;
  assign _007_[0] = _007_[1] ? 1'h0 : _008_[0];
  assign _006_[0] = _070_ ? 1'h1 : _007_[0];
  assign _006_[1] = _070_ ? 1'h1 : _007_[1];
  assign _006_[2] = _070_ ? 1'h0 : _007_[0];
  assign _004_[0] = fifo_full ? 1'h0 : _005_[0];
  assign _004_[1] = ~fifo_full;
  assign _002_[1] = _002_[0] ? 1'h0 : _003_[1];
  assign _084_[7] = ~_009_[0];
  assign _083_[7] = _009_[1] ? 1'h0 : _084_[7];
  assign _083_[0] = _009_[1] ? 1'h0 : _009_[0];
  assign _000_[5] = _009_[2] ? _083_[0] : _009_[1];
  assign _026_[0] = _001_[0] & _085_;
  assign _046_ = _006_[0] & _087_;
  assign _047_ = _004_[1] & _053_;
  assign _048_ = _004_[0] & _088_;
  assign _026_[3] = _002_[0] & _089_;
  assign _049_ = _006_[1] & _087_;
  assign _029_[2] = _004_[1] & _088_;
  assign _032_[3] = _002_[1] & _089_;
  assign _029_[0] = _001_[1] & _085_;
  assign _051_ = fifo_full & _086_;
  assign _052_ = _006_[2] & _087_;
  assign _054_ = fifo_full & _088_;
  assign next_state[0] = _025_ ? _028_ : 1'hx;
  assign next_state[1] = _025_ ? _031_ : 1'hx;
  assign next_state[2] = _025_ ? _034_ : 1'hx;
  assign _084_[6:0] = { 5'h00, _009_[0], _009_[0] };
  assign { _083_[6:3], _083_[1] } = { 1'h0, _009_[1], 2'h0, _009_[0] };
  assign _008_[2:1] = { _008_[0], 1'h0 };
  assign _007_[2] = _007_[0];
  assign _005_[2:1] = 2'h1;
  assign _004_[2] = fifo_full;
  assign { _003_[2], _003_[0] } = { _003_[1], 1'h0 };
  assign _001_[2] = _001_[1];
  assign _002_[2] = _002_[1];
endmodule

module router_reg(clock, resetn, pkt_valid, fifo_full, rst_int_reg, detect_add, ld_state, laf_state, full_state, lfd_state, data_in, parity_done, low_pkt_valid, err, dout);
  input clock;
  wire clock;
  input resetn;
  wire resetn;
  input pkt_valid;
  wire pkt_valid;
  input fifo_full;
  wire fifo_full;
  input rst_int_reg;
  wire rst_int_reg;
  input detect_add;
  wire detect_add;
  input ld_state;
  wire ld_state;
  input laf_state;
  wire laf_state;
  input full_state;
  wire full_state;
  input lfd_state;
  wire lfd_state;
  input [7:0] data_in;
  wire [7:0] data_in;
  output parity_done;
  reg parity_done;
  output low_pkt_valid;
  reg low_pkt_valid;
  output err;
  reg err;
  output [7:0] dout;
  reg [7:0] dout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire [3:0] _005_;
  wire [1:0] _006_;
  wire [7:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire [7:0] _024_;
  wire [7:0] _025_;
  wire [7:0] _026_;
  wire [7:0] _027_;
  wire [7:0] _028_;
  wire [7:0] _029_;
  wire [7:0] _030_;
  wire [7:0] _031_;
  wire [7:0] _032_;
  reg [7:0] full_state_reg;
  reg [7:0] header_reg;
  reg [7:0] packet_parity_reg;
  reg [7:0] parity_reg;
  always @(posedge clock)
    if (!resetn) header_reg[0] <= 1'h0;
    else if (_009_) header_reg[0] <= data_in[0];
  always @(posedge clock)
    if (!resetn) header_reg[1] <= 1'h0;
    else if (_009_) header_reg[1] <= data_in[1];
  always @(posedge clock)
    if (!resetn) header_reg[2] <= 1'h0;
    else if (_009_) header_reg[2] <= data_in[2];
  always @(posedge clock)
    if (!resetn) header_reg[3] <= 1'h0;
    else if (_009_) header_reg[3] <= data_in[3];
  always @(posedge clock)
    if (!resetn) header_reg[4] <= 1'h0;
    else if (_009_) header_reg[4] <= data_in[4];
  always @(posedge clock)
    if (!resetn) header_reg[5] <= 1'h0;
    else if (_009_) header_reg[5] <= data_in[5];
  always @(posedge clock)
    if (!resetn) header_reg[6] <= 1'h0;
    else if (_009_) header_reg[6] <= data_in[6];
  always @(posedge clock)
    if (!resetn) header_reg[7] <= 1'h0;
    else if (_009_) header_reg[7] <= data_in[7];
  always @(posedge clock)
    if (!resetn) dout[0] <= 1'h0;
    else if (_002_) dout[0] <= _029_[0];
  always @(posedge clock)
    if (!resetn) dout[1] <= 1'h0;
    else if (_002_) dout[1] <= _029_[1];
  always @(posedge clock)
    if (!resetn) dout[2] <= 1'h0;
    else if (_002_) dout[2] <= _029_[2];
  always @(posedge clock)
    if (!resetn) dout[3] <= 1'h0;
    else if (_002_) dout[3] <= _029_[3];
  always @(posedge clock)
    if (!resetn) dout[4] <= 1'h0;
    else if (_002_) dout[4] <= _029_[4];
  always @(posedge clock)
    if (!resetn) dout[5] <= 1'h0;
    else if (_002_) dout[5] <= _029_[5];
  always @(posedge clock)
    if (!resetn) dout[6] <= 1'h0;
    else if (_002_) dout[6] <= _029_[6];
  always @(posedge clock)
    if (!resetn) dout[7] <= 1'h0;
    else if (_002_) dout[7] <= _029_[7];
  always @(posedge clock)
    if (!resetn) full_state_reg[0] <= 1'h0;
    else if (_011_) full_state_reg[0] <= data_in[0];
  always @(posedge clock)
    if (!resetn) full_state_reg[1] <= 1'h0;
    else if (_011_) full_state_reg[1] <= data_in[1];
  always @(posedge clock)
    if (!resetn) full_state_reg[2] <= 1'h0;
    else if (_011_) full_state_reg[2] <= data_in[2];
  always @(posedge clock)
    if (!resetn) full_state_reg[3] <= 1'h0;
    else if (_011_) full_state_reg[3] <= data_in[3];
  always @(posedge clock)
    if (!resetn) full_state_reg[4] <= 1'h0;
    else if (_011_) full_state_reg[4] <= data_in[4];
  always @(posedge clock)
    if (!resetn) full_state_reg[5] <= 1'h0;
    else if (_011_) full_state_reg[5] <= data_in[5];
  always @(posedge clock)
    if (!resetn) full_state_reg[6] <= 1'h0;
    else if (_011_) full_state_reg[6] <= data_in[6];
  always @(posedge clock)
    if (!resetn) full_state_reg[7] <= 1'h0;
    else if (_011_) full_state_reg[7] <= data_in[7];
  always @(posedge clock)
    if (_020_) parity_reg[0] <= 1'h0;
    else if (_001_) parity_reg[0] <= _026_[0];
  always @(posedge clock)
    if (_020_) parity_reg[1] <= 1'h0;
    else if (_001_) parity_reg[1] <= _026_[1];
  always @(posedge clock)
    if (_020_) parity_reg[2] <= 1'h0;
    else if (_001_) parity_reg[2] <= _026_[2];
  always @(posedge clock)
    if (_020_) parity_reg[3] <= 1'h0;
    else if (_001_) parity_reg[3] <= _026_[3];
  always @(posedge clock)
    if (_020_) parity_reg[4] <= 1'h0;
    else if (_001_) parity_reg[4] <= _026_[4];
  always @(posedge clock)
    if (_020_) parity_reg[5] <= 1'h0;
    else if (_001_) parity_reg[5] <= _026_[5];
  always @(posedge clock)
    if (_020_) parity_reg[6] <= 1'h0;
    else if (_001_) parity_reg[6] <= _026_[6];
  always @(posedge clock)
    if (_020_) parity_reg[7] <= 1'h0;
    else if (_001_) parity_reg[7] <= _026_[7];
  always @(posedge clock)
    if (!resetn) packet_parity_reg[0] <= 1'h0;
    else if (parity_done) packet_parity_reg[0] <= data_in[0];
  always @(posedge clock)
    if (!resetn) packet_parity_reg[1] <= 1'h0;
    else if (parity_done) packet_parity_reg[1] <= data_in[1];
  always @(posedge clock)
    if (!resetn) packet_parity_reg[2] <= 1'h0;
    else if (parity_done) packet_parity_reg[2] <= data_in[2];
  always @(posedge clock)
    if (!resetn) packet_parity_reg[3] <= 1'h0;
    else if (parity_done) packet_parity_reg[3] <= data_in[3];
  always @(posedge clock)
    if (!resetn) packet_parity_reg[4] <= 1'h0;
    else if (parity_done) packet_parity_reg[4] <= data_in[4];
  always @(posedge clock)
    if (!resetn) packet_parity_reg[5] <= 1'h0;
    else if (parity_done) packet_parity_reg[5] <= data_in[5];
  always @(posedge clock)
    if (!resetn) packet_parity_reg[6] <= 1'h0;
    else if (parity_done) packet_parity_reg[6] <= data_in[6];
  always @(posedge clock)
    if (!resetn) packet_parity_reg[7] <= 1'h0;
    else if (parity_done) packet_parity_reg[7] <= data_in[7];
  always @(posedge clock)
    if (_020_) parity_done <= 1'h0;
    else if (_000_) parity_done <= _023_;
  always @(posedge clock)
    if (!resetn) err <= 1'h0;
    else if (parity_done) err <= _021_;
  always @(posedge clock)
    if (_019_) low_pkt_valid <= 1'h0;
    else if (_008_) low_pkt_valid <= 1'h1;
  assign _030_[0] = parity_reg[0] ^ header_reg[0];
  assign _030_[1] = parity_reg[1] ^ header_reg[1];
  assign _030_[2] = parity_reg[2] ^ header_reg[2];
  assign _030_[3] = parity_reg[3] ^ header_reg[3];
  assign _030_[4] = parity_reg[4] ^ header_reg[4];
  assign _030_[5] = parity_reg[5] ^ header_reg[5];
  assign _030_[6] = parity_reg[6] ^ header_reg[6];
  assign _030_[7] = parity_reg[7] ^ header_reg[7];
  assign _031_[0] = parity_reg[0] ^ data_in[0];
  assign _031_[1] = parity_reg[1] ^ data_in[1];
  assign _031_[2] = parity_reg[2] ^ data_in[2];
  assign _031_[3] = parity_reg[3] ^ data_in[3];
  assign _031_[4] = parity_reg[4] ^ data_in[4];
  assign _031_[5] = parity_reg[5] ^ data_in[5];
  assign _031_[6] = parity_reg[6] ^ data_in[6];
  assign _031_[7] = parity_reg[7] ^ data_in[7];
  assign _032_[0] = parity_reg[0] ^ full_state_reg[0];
  assign _032_[1] = parity_reg[1] ^ full_state_reg[1];
  assign _032_[2] = parity_reg[2] ^ full_state_reg[2];
  assign _032_[3] = parity_reg[3] ^ full_state_reg[3];
  assign _032_[4] = parity_reg[4] ^ full_state_reg[4];
  assign _032_[5] = parity_reg[5] ^ full_state_reg[5];
  assign _032_[6] = parity_reg[6] ^ full_state_reg[6];
  assign _032_[7] = parity_reg[7] ^ full_state_reg[7];
  assign _007_[0] = parity_reg[0] ^ packet_parity_reg[0];
  assign _007_[1] = parity_reg[1] ^ packet_parity_reg[1];
  assign _007_[2] = parity_reg[2] ^ packet_parity_reg[2];
  assign _007_[3] = parity_reg[3] ^ packet_parity_reg[3];
  assign _007_[4] = parity_reg[4] ^ packet_parity_reg[4];
  assign _007_[5] = parity_reg[5] ^ packet_parity_reg[5];
  assign _007_[6] = parity_reg[6] ^ packet_parity_reg[6];
  assign _007_[7] = parity_reg[7] ^ packet_parity_reg[7];
  assign _003_ = lfd_state | laf_state;
  assign _002_ = _003_ | _010_;
  assign _004_ = lfd_state | full_state;
  assign _001_ = _004_ | _010_;
  assign _000_ = _012_ | _014_;
  assign _005_[0] = _007_[0] | _007_[1];
  assign _005_[1] = _007_[2] | _007_[3];
  assign _005_[2] = _007_[4] | _007_[5];
  assign _005_[3] = _007_[6] | _007_[7];
  assign _006_[0] = _005_[0] | _005_[1];
  assign _006_[1] = _005_[2] | _005_[3];
  assign _021_ = _006_[0] | _006_[1];
  assign _017_ = ~fifo_full;
  assign _018_ = ~parity_done;
  assign _015_ = ~resetn;
  assign _016_ = ~pkt_valid;
  assign _009_ = detect_add & pkt_valid;
  assign _011_ = ld_state & fifo_full;
  assign _020_ = _015_ | detect_add;
  assign _010_ = ld_state & _017_;
  assign _012_ = _010_ & _016_;
  assign _013_ = laf_state & low_pkt_valid;
  assign _014_ = _013_ & _018_;
  assign _019_ = _015_ | rst_int_reg;
  assign _008_ = ld_state & _016_;
  assign _022_ = _014_ ? 1'h1 : 1'hx;
  assign _023_ = _012_ ? 1'h1 : _022_;
  assign _024_[0] = full_state ? _032_[0] : 1'hx;
  assign _024_[1] = full_state ? _032_[1] : 1'hx;
  assign _024_[2] = full_state ? _032_[2] : 1'hx;
  assign _024_[3] = full_state ? _032_[3] : 1'hx;
  assign _024_[4] = full_state ? _032_[4] : 1'hx;
  assign _024_[5] = full_state ? _032_[5] : 1'hx;
  assign _024_[6] = full_state ? _032_[6] : 1'hx;
  assign _024_[7] = full_state ? _032_[7] : 1'hx;
  assign _025_[0] = _010_ ? _031_[0] : _024_[0];
  assign _025_[1] = _010_ ? _031_[1] : _024_[1];
  assign _025_[2] = _010_ ? _031_[2] : _024_[2];
  assign _025_[3] = _010_ ? _031_[3] : _024_[3];
  assign _025_[4] = _010_ ? _031_[4] : _024_[4];
  assign _025_[5] = _010_ ? _031_[5] : _024_[5];
  assign _025_[6] = _010_ ? _031_[6] : _024_[6];
  assign _025_[7] = _010_ ? _031_[7] : _024_[7];
  assign _026_[0] = lfd_state ? _030_[0] : _025_[0];
  assign _026_[1] = lfd_state ? _030_[1] : _025_[1];
  assign _026_[2] = lfd_state ? _030_[2] : _025_[2];
  assign _026_[3] = lfd_state ? _030_[3] : _025_[3];
  assign _026_[4] = lfd_state ? _030_[4] : _025_[4];
  assign _026_[5] = lfd_state ? _030_[5] : _025_[5];
  assign _026_[6] = lfd_state ? _030_[6] : _025_[6];
  assign _026_[7] = lfd_state ? _030_[7] : _025_[7];
  assign _027_[0] = laf_state ? full_state_reg[0] : 1'hx;
  assign _027_[1] = laf_state ? full_state_reg[1] : 1'hx;
  assign _027_[2] = laf_state ? full_state_reg[2] : 1'hx;
  assign _027_[3] = laf_state ? full_state_reg[3] : 1'hx;
  assign _027_[4] = laf_state ? full_state_reg[4] : 1'hx;
  assign _027_[5] = laf_state ? full_state_reg[5] : 1'hx;
  assign _027_[6] = laf_state ? full_state_reg[6] : 1'hx;
  assign _027_[7] = laf_state ? full_state_reg[7] : 1'hx;
  assign _028_[0] = _010_ ? data_in[0] : _027_[0];
  assign _028_[1] = _010_ ? data_in[1] : _027_[1];
  assign _028_[2] = _010_ ? data_in[2] : _027_[2];
  assign _028_[3] = _010_ ? data_in[3] : _027_[3];
  assign _028_[4] = _010_ ? data_in[4] : _027_[4];
  assign _028_[5] = _010_ ? data_in[5] : _027_[5];
  assign _028_[6] = _010_ ? data_in[6] : _027_[6];
  assign _028_[7] = _010_ ? data_in[7] : _027_[7];
  assign _029_[0] = lfd_state ? header_reg[0] : _028_[0];
  assign _029_[1] = lfd_state ? header_reg[1] : _028_[1];
  assign _029_[2] = lfd_state ? header_reg[2] : _028_[2];
  assign _029_[3] = lfd_state ? header_reg[3] : _028_[3];
  assign _029_[4] = lfd_state ? header_reg[4] : _028_[4];
  assign _029_[5] = lfd_state ? header_reg[5] : _028_[5];
  assign _029_[6] = lfd_state ? header_reg[6] : _028_[6];
  assign _029_[7] = lfd_state ? header_reg[7] : _028_[7];
endmodule

module router_sync(detect_add, write_enb_reg, clock, resetn, read_enb_0, read_enb_1, read_enb_2, empty_0, empty_1, empty_2, full_0, full_1, full_2, data_in, write_enb, soft_reset_0, soft_reset_1, soft_reset_2, vld_out_0, vld_out_1, vld_out_2
, fifo_full);
  input detect_add;
  wire detect_add;
  input write_enb_reg;
  wire write_enb_reg;
  input clock;
  wire clock;
  input resetn;
  wire resetn;
  input read_enb_0;
  wire read_enb_0;
  input read_enb_1;
  wire read_enb_1;
  input read_enb_2;
  wire read_enb_2;
  input empty_0;
  wire empty_0;
  input empty_1;
  wire empty_1;
  input empty_2;
  wire empty_2;
  input full_0;
  wire full_0;
  input full_1;
  wire full_1;
  input full_2;
  wire full_2;
  input [1:0] data_in;
  wire [1:0] data_in;
  output [2:0] write_enb;
  wire [2:0] write_enb;
  output soft_reset_0;
  reg soft_reset_0;
  output soft_reset_1;
  reg soft_reset_1;
  output soft_reset_2;
  reg soft_reset_2;
  output vld_out_0;
  wire vld_out_0;
  output vld_out_1;
  wire vld_out_1;
  output vld_out_2;
  wire vld_out_2;
  output fifo_full;
  wire fifo_full;
  wire [2:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire [1:0] _018_;
  wire _019_;
  wire [1:0] _020_;
  wire _021_;
  wire [1:0] _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire [31:0] _050_;
  wire [31:0] _051_;
  wire [31:0] _052_;
  wire [31:0] _053_;
  wire [31:0] _054_;
  wire [31:0] _055_;
  wire [31:0] _056_;
  wire [31:0] _057_;
  wire [31:0] _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  reg [1:0] addr;
  reg [4:0] count_0;
  reg [4:0] count_1;
  reg [4:0] count_2;
  always @(posedge clock)
    if (_017_) soft_reset_2 <= 1'h0;
    else soft_reset_2 <= _040_;
  always @(posedge clock)
    if (!resetn) addr[0] <= 1'h0;
    else if (detect_add) addr[0] <= data_in[0];
  always @(posedge clock)
    if (!resetn) addr[1] <= 1'h0;
    else if (detect_add) addr[1] <= data_in[1];
  always @(posedge clock)
    if (_016_) count_0[0] <= 1'h0;
    else count_0[0] <= _057_[0];
  always @(posedge clock)
    if (_016_) count_0[1] <= 1'h0;
    else count_0[1] <= _058_[1];
  always @(posedge clock)
    if (_016_) count_0[2] <= 1'h0;
    else count_0[2] <= _058_[2];
  always @(posedge clock)
    if (_016_) count_0[3] <= 1'h0;
    else count_0[3] <= _058_[3];
  always @(posedge clock)
    if (_016_) count_0[4] <= 1'h0;
    else count_0[4] <= _058_[4];
  always @(posedge clock)
    if (_015_) soft_reset_0 <= 1'h0;
    else soft_reset_0 <= _041_;
  always @(posedge clock)
    if (_014_) count_1[0] <= 1'h0;
    else count_1[0] <= _051_[0];
  always @(posedge clock)
    if (_014_) count_1[1] <= 1'h0;
    else count_1[1] <= _052_[1];
  always @(posedge clock)
    if (_014_) count_1[2] <= 1'h0;
    else count_1[2] <= _052_[2];
  always @(posedge clock)
    if (_014_) count_1[3] <= 1'h0;
    else count_1[3] <= _052_[3];
  always @(posedge clock)
    if (_014_) count_1[4] <= 1'h0;
    else count_1[4] <= _052_[4];
  always @(posedge clock)
    if (_013_) soft_reset_1 <= 1'h0;
    else soft_reset_1 <= _042_;
  always @(posedge clock)
    if (_012_) count_2[0] <= 1'h0;
    else count_2[0] <= _054_[0];
  always @(posedge clock)
    if (_012_) count_2[1] <= 1'h0;
    else count_2[1] <= _055_[1];
  always @(posedge clock)
    if (_012_) count_2[2] <= 1'h0;
    else count_2[2] <= _055_[2];
  always @(posedge clock)
    if (_012_) count_2[3] <= 1'h0;
    else count_2[3] <= _055_[3];
  always @(posedge clock)
    if (_012_) count_2[4] <= 1'h0;
    else count_2[4] <= _055_[4];
  assign _054_[0] = ~count_2[0];
  assign _057_[0] = ~count_0[0];
  assign _001_ = ~addr[0];
  assign _002_ = ~addr[1];
  assign _003_ = ~count_0[3];
  assign _004_ = ~count_0[2];
  assign _005_ = ~count_0[4];
  assign _006_ = ~count_1[3];
  assign _007_ = ~count_1[2];
  assign _051_[0] = ~count_1[0];
  assign _008_ = ~count_1[4];
  assign _009_ = ~count_2[3];
  assign _010_ = ~count_2[2];
  assign _011_ = ~count_2[4];
  assign _058_[1] = count_0[1] ^ count_0[0];
  assign _058_[2] = count_0[2] ^ _056_[1];
  assign _058_[3] = count_0[3] ^ _056_[2];
  assign _058_[4] = count_0[4] ^ _056_[3];
  assign _052_[1] = count_1[1] ^ count_1[0];
  assign _052_[2] = count_1[2] ^ _050_[1];
  assign _052_[3] = count_1[3] ^ _050_[2];
  assign _052_[4] = count_1[4] ^ _050_[3];
  assign _055_[1] = count_2[1] ^ count_2[0];
  assign _055_[2] = count_2[2] ^ _053_[1];
  assign _055_[3] = count_2[3] ^ _053_[2];
  assign _055_[4] = count_2[4] ^ _053_[3];
  assign _056_[2] = count_0[2] & _056_[1];
  assign _056_[3] = _061_ & _056_[1];
  assign _061_ = count_0[3] & count_0[2];
  assign _056_[1] = count_0[1] & count_0[0];
  assign _050_[2] = count_1[2] & _050_[1];
  assign _050_[3] = _059_ & _050_[1];
  assign _059_ = count_1[3] & count_1[2];
  assign _050_[1] = count_1[1] & count_1[0];
  assign _053_[2] = count_2[2] & _053_[1];
  assign _053_[3] = _060_ & _053_[1];
  assign _060_ = count_2[3] & count_2[2];
  assign _053_[1] = count_2[1] & count_2[0];
  assign _015_ = empty_0 | _047_;
  assign _016_ = _015_ | _041_;
  assign _013_ = empty_1 | _049_;
  assign _014_ = _013_ | _042_;
  assign _017_ = empty_2 | _045_;
  assign _012_ = _017_ | _040_;
  assign _018_[0] = _057_[0] | count_0[1];
  assign _018_[1] = _004_ | _003_;
  assign _019_ = _018_[0] | _018_[1];
  assign _032_ = _019_ | _005_;
  assign _020_[0] = _051_[0] | count_1[1];
  assign _020_[1] = _007_ | _006_;
  assign _021_ = _020_[0] | _020_[1];
  assign _033_ = _021_ | _008_;
  assign _022_[0] = _054_[0] | count_2[1];
  assign _022_[1] = _010_ | _009_;
  assign _023_ = _022_[0] | _022_[1];
  assign _034_ = _023_ | _011_;
  assign _035_ = addr[0] | _002_;
  assign _036_ = _001_ | addr[1];
  assign _024_ = _028_ | _027_;
  assign _025_ = _024_ | _026_;
  assign _029_ = _037_ | _038_;
  assign _030_ = _029_ | _039_;
  assign _031_ = addr[0] | addr[1];
  assign _043_ = ~resetn;
  assign _028_ = ~_035_;
  assign _027_ = ~_036_;
  assign _026_ = ~_031_;
  assign _046_ = _043_ | soft_reset_0;
  assign _047_ = _046_ | read_enb_0;
  assign _048_ = _043_ | soft_reset_1;
  assign _049_ = _048_ | read_enb_1;
  assign _044_ = _043_ | soft_reset_2;
  assign _045_ = _044_ | read_enb_2;
  assign _040_ = ~_034_;
  assign _042_ = ~_033_;
  assign _041_ = ~_032_;
  assign write_enb[0] = write_enb_reg ? _000_[0] : 1'h0;
  assign write_enb[1] = write_enb_reg ? _000_[1] : 1'h0;
  assign write_enb[2] = write_enb_reg ? _000_[2] : 1'h0;
  assign _037_ = full_2 & _028_;
  assign _038_ = full_1 & _027_;
  assign _039_ = full_0 & _026_;
  assign vld_out_0 = ~empty_0;
  assign vld_out_1 = ~empty_1;
  assign vld_out_2 = ~empty_2;
  assign _000_[0] = _025_ ? _026_ : 1'h0;
  assign _000_[1] = _025_ ? _027_ : 1'h0;
  assign _000_[2] = _025_ ? _028_ : 1'h0;
  assign fifo_full = _025_ ? _030_ : 1'h0;
  assign { _055_[31:5], _055_[0] } = { 26'h0000000, _053_[4], _054_[0] };
  assign _057_[31:1] = { 27'h0000000, count_0[4:1] };
  assign { _052_[31:5], _052_[0] } = { 26'h0000000, _050_[4], _051_[0] };
  assign _051_[31:1] = { 27'h0000000, count_1[4:1] };
  assign { _058_[31:5], _058_[0] } = { 26'h0000000, _056_[4], _057_[0] };
  assign { _053_[31:5], _053_[0] } = { 27'h0000000, count_2[0] };
  assign _054_[31:1] = { 27'h0000000, count_2[4:1] };
  assign { _056_[31:5], _056_[0] } = { 27'h0000000, count_0[0] };
  assign { _050_[31:5], _050_[0] } = { 27'h0000000, count_1[0] };
endmodule

module router_top(clock, resetn, read_enb_0, read_enb_1, read_enb_2, data_in, pkt_valid, data_out_0, data_out_1, data_out_2, vld_out_0, vld_out_1, vld_out_2, error, busy);
  input clock;
  wire clock;
  input resetn;
  wire resetn;
  input read_enb_0;
  wire read_enb_0;
  input read_enb_1;
  wire read_enb_1;
  input read_enb_2;
  wire read_enb_2;
  input [7:0] data_in;
  wire [7:0] data_in;
  input pkt_valid;
  wire pkt_valid;
  output [7:0] data_out_0;
  wire [7:0] data_out_0;
  output [7:0] data_out_1;
  wire [7:0] data_out_1;
  output [7:0] data_out_2;
  wire [7:0] data_out_2;
  output vld_out_0;
  wire vld_out_0;
  output vld_out_1;
  wire vld_out_1;
  output vld_out_2;
  wire vld_out_2;
  output error;
  wire error;
  output busy;
  wire busy;
  wire detect_add;
  wire [7:0] dout;
  wire empty_0;
  wire empty_1;
  wire empty_2;
  wire fifo_full;
  wire full_0;
  wire full_1;
  wire full_2;
  wire full_state;
  wire laf_state;
  wire ld_state;
  wire lfd_state;
  wire low_pkt_valid;
  wire parity_done;
  wire rst_int_reg;
  wire soft_reset_0;
  wire soft_reset_1;
  wire soft_reset_2;
  wire [2:0] write_enb;
  wire write_enb_reg;
  router_fifo fifo0_inst (
    .clock(clock),
    .data_in(dout),
    .data_out(data_out_0),
    .empty(empty_0),
    .full(full_0),
    .lfd_state(lfd_state),
    .read_enb(read_enb_0),
    .resetn(resetn),
    .soft_reset(soft_reset_0),
    .write_enb(write_enb[0])
  );
  router_fifo fifo1_inst (
    .clock(clock),
    .data_in(dout),
    .data_out(data_out_1),
    .empty(empty_1),
    .full(full_1),
    .lfd_state(lfd_state),
    .read_enb(read_enb_1),
    .resetn(resetn),
    .soft_reset(soft_reset_1),
    .write_enb(write_enb[1])
  );
  router_fifo fifo2_inst (
    .clock(clock),
    .data_in(dout),
    .data_out(data_out_2),
    .empty(empty_2),
    .full(full_2),
    .lfd_state(lfd_state),
    .read_enb(read_enb_2),
    .resetn(resetn),
    .soft_reset(soft_reset_2),
    .write_enb(write_enb[2])
  );
  router_fsm fsm_inst (
    .busy(busy),
    .clock(clock),
    .data_in(data_in[1:0]),
    .detect_add(detect_add),
    .fifo_empty_0(empty_0),
    .fifo_empty_1(empty_1),
    .fifo_empty_2(empty_2),
    .fifo_full(fifo_full),
    .full_state(full_state),
    .laf_state(laf_state),
    .ld_state(ld_state),
    .lfd_state(lfd_state),
    .low_pkt_valid(low_pkt_valid),
    .parity_done(parity_done),
    .pkt_valid(pkt_valid),
    .resetn(resetn),
    .rst_int_reg(rst_int_reg),
    .soft_reset_0(soft_reset_0),
    .soft_reset_1(soft_reset_1),
    .soft_reset_2(soft_reset_2),
    .write_enb_reg(write_enb_reg)
  );
  router_reg reg_inst (
    .clock(clock),
    .data_in(data_in),
    .detect_add(detect_add),
    .dout(dout),
    .err(error),
    .fifo_full(fifo_full),
    .full_state(full_state),
    .laf_state(laf_state),
    .ld_state(ld_state),
    .lfd_state(lfd_state),
    .low_pkt_valid(low_pkt_valid),
    .parity_done(parity_done),
    .pkt_valid(pkt_valid),
    .resetn(resetn),
    .rst_int_reg(rst_int_reg)
  );
  router_sync sync_inst (
    .clock(clock),
    .data_in(data_in[1:0]),
    .detect_add(detect_add),
    .empty_0(empty_0),
    .empty_1(empty_1),
    .empty_2(empty_2),
    .fifo_full(fifo_full),
    .full_0(full_0),
    .full_1(full_1),
    .full_2(full_2),
    .read_enb_0(read_enb_0),
    .read_enb_1(read_enb_1),
    .read_enb_2(read_enb_2),
    .resetn(resetn),
    .soft_reset_0(soft_reset_0),
    .soft_reset_1(soft_reset_1),
    .soft_reset_2(soft_reset_2),
    .vld_out_0(vld_out_0),
    .vld_out_1(vld_out_1),
    .vld_out_2(vld_out_2),
    .write_enb(write_enb),
    .write_enb_reg(write_enb_reg)
  );
endmodule
